import type { BackendMaterial } from './backendMaterial';
import type { BackendNote } from './backendNote';

export interface BackendPatient {
  _id?: string;
  id: number;
  patientId: number;
  name: string;
  surname: string;
  birthdate: string;
  nationality: string;
  typeOfIdentification: string;
  identification: string;
  sex: string;
  email: string;
  phone: string;
  age: number;
  ageRange: string;
  rangoEtario: string;
  isEnabled: boolean;
  nextNoteId: number;
  nextMaterialId: number;
  admissionDate: string;
  __v?: number;
  materials?: BackendMaterial[];
  notes?: BackendNote[];
  principalMotive?: string | null;
  actualSymptoms?: string | null;
  recentEvents?: string | null;
  previousDiagnosis?: string | null;
  profesionalObservations?: string | null;
  keyWords?: string | null;
  failedActs?: string | null;
  interconsulation?: string | null;
  patientEvolution?: string | null;
  sessionDay?: string | null;
  modality?: string | null;
  sessionDuration?: number | null;
  sessionFrequency?: string | null;
  preferedContact?: string | null;
}
